package com.example.demo.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.util.Date;
/**
 * Represents a product with attributes like name, category, price, stock, and expiration date.
 * This class is annotated for use with JPA to map to a database table named 'product'.
 * Lombok annotations provide automatic generation of getters, setters, toString, and constructors.
 */
@Entity
@Table(name="product")
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
@ToString
public class Product {
    /**
     * The unique identifier for the product. This field is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The name of the product. It is unique and cannot be null.
     */
    @Column(unique=true, nullable=false)
    private String name;

    /**
     * The category of the product, represented as an enum. This field cannot be null.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Category category;

    /**
     * The price of the product in integer units. This field cannot be null.
     */
    @Column(nullable = false)
    private int price;

    /**
     * The stock quantity of the product. This field cannot be null.
     */
    @Column(nullable=false)
    private int stock;

    /**
     * The expiration date of the product, represented as a LocalDate. This field cannot be null.
     */
    @Column(nullable = false)
    private LocalDate expirationDate;

    @Column(nullable = false)
    private String image;

    @Column(nullable = false)
    private int quantity;

    @Column
    private String description;



    public Product(String name, Category category, int price, int stock, LocalDate expirationDate, String image, int quantity){
        this.name = name;
        this.category = category;
        this.price = price;
        this.stock = stock;
        this.expirationDate = expirationDate;
        this.image = image;
        this.quantity = quantity;

    }

    public Product(String name, Category category, int price, int stock, LocalDate expirationDate, String image){
        this.name = name;
        this.category = category;
        this.price = price;
        this.stock = stock;
        this.expirationDate = expirationDate;
        this.image = image;
    }




}
